# -*- coding: utf-8 -*-
"""Day 72 (Salary).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXIKQfy-SUr3jQ8j6ghGs9mRn3Yy3th0
"""

import pandas as pd

# Load the data from the CSV file.
df = pd.read_csv('salaries_by_college_major.csv')


# View the first few rows of the table
df.head()

# Check the shape of the table (number of rows and columns)
df.shape

# List all column names
df.columns

# Check for missing values in the table
df.isna()

# Count the number of missing values in each column
df.isna().sum()



# Remove rows with missing values
clean_df = df.dropna()

# View the last few rows of the cleaned table
clean_df.tail()



# View the 'Starting Median Salary' column
clean_df['Starting Median Salary']

# Find the maximum starting median salary
clean_df['Starting Median Salary'].max()

# Find the index of the row with the highest starting median salary
clean_df['Starting Median Salary'].idxmax()



# Find the major with the highest starting median salary
clean_df['Undergraduate Major'].loc[43]

# Alternative way to get the major by index
clean_df.loc[43, 'Undergraduate Major']

# Another way to get the major by index
clean_df['Undergraduate Major'].loc[43]

# Alternative syntax (not recommended)
clean_df['Undergraduate Major'][43]

# Get the entire row by index
clean_df.loc[43]



# Find the major with the highest mid-career median salary
clean_df['Undergraduate Major'].loc[clean_df['Mid-Career Median Salary'].idxmax()]

# Find the highest mid-career median salary
clean_df['Mid-Career Median Salary'].max()



# Find the major with the lowest starting median salary
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

# Find the lowest starting median salary
clean_df['Starting Median Salary'].min()



# Get the entire row with the lowest mid-career median salary
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

# Calculate the difference between the 90th and 10th percentile mid-career salaries
clean_df['Spread'] = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

# View the 'Starting Median Salary' column
clean_df['Starting Median Salary']

# View only the 'Undergraduate Major' and 'Starting Median Salary' columns
clean_df[['Undergraduate Major','Starting Median Salary']]



# Sort the table by starting median salary
clean_df.sort_values('Starting Median Salary')

# Find majors with the lowest salary spread
clean_df.sort_values('Spread')[['Undergraduate Major', 'Spread']].head()

# Find majors with the highest 90th percentile mid-career salary
clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False).head()

# Find majors with the largest salary spread
clean_df.sort_values('Spread', ascending=False).head()

# Count the number of majors in each group (STEM, HASS, Business)
clean_df.groupby('Group').count()

# Set display format for numbers (commas and two decimal places)
pd.options.display.float_format = '{:,.2f}'.format



# List of numeric columns for grouping
numeric_cols = ['Spread', 'Starting Median Salary', 'Mid-Career Median Salary',
                'Mid-Career 10th Percentile Salary', 'Mid-Career 90th Percentile Salary']

# Calculate the mean for each group, only for numeric columns
clean_df.groupby('Group')[numeric_cols].mean()
